### ISSUE TITLE
Access Denied error on Mac

### ISSUE THREAD

**Issue by dlaidlaw** [28mm/blast-radius#53]
Mac OSX 10.13.6 (High Sierra)
Python version: 2.7.10
Running : blast-radius --serve .

```
 * Debug mode: off
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [28/Nov/2018 10:50:24] "GET / HTTP/1.1" 200 -
Error loading state: AccessDenied: Access Denied
	status code: 403, request id: F5D440E18F1778DA, host id: hWAk0q67MYM+a7gao50Ytkw4+b0s8jPfeFZl7CEbmOIyU4EavpMuLxf7pNJzYra3sSCmApBQxwA=
[2018-11-28 10:50:27,048] ERROR in app: Exception on /graph.svg [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.7/site-packages/blastradius/server/server.py", line 32, in graph_svg
    dot = DotGraph('', file_contents=run_tf_graph())
  File "/usr/local/lib/python3.7/site-packages/blastradius/server/server.py", line 71, in run_tf_graph
    raise
RuntimeError: No active exception to reraise
127.0.0.1 - - [28/Nov/2018 10:50:27] "GET /graph.svg HTTP/1.1" 500 -
```

Any Hints?

**Comment by dlaidlaw** [comment]
In my case this is because the terraform command needs a command line option to configure the backend. Doing this with environment variables worked. So, I solved my own problem.
