### ISSUE TITLE
Error when reading one of my state files

### ISSUE THREAD

**Issue by red8888** [28mm/blast-radius#56]
`Terraform v0.11.10`

Im seeing this error (this is a valid tf config that applies successfully). Some other tf state it seems to work fine with, but this one it no like

> * Debug mode: off
>  * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
> 127.0.0.1 - - [21/Jan/2019 09:38:05] "GET / HTTP/1.1" 200 -
> 127.0.0.1 - - [21/Jan/2019 09:38:10] "GET / HTTP/1.1" 200 -
> 127.0.0.1 - - [21/Jan/2019 09:38:12] "GET /graph.svg HTTP/1.1" 200 -
> [2019-01-21 09:38:14,328] ERROR in app: Exception on /graph.json [GET]
> Traceback (most recent call last):
>   File "/Users/meee/.pyenv/versions/3.6.5/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
>     response = self.full_dispatch_request()
>   File "/Users/meee/.pyenv/versions/3.6.5/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
>     rv = self.handle_user_exception(e)
>   File "/Users/meee/.pyenv/versions/3.6.5/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
>     reraise(exc_type, exc_value, tb)
>   File "/Users/meee/.pyenv/versions/3.6.5/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
>     raise value
>   File "/Users/meee/.pyenv/versions/3.6.5/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
>     rv = self.dispatch_request()
>   File "/Users/meee/.pyenv/versions/3.6.5/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
>     return self.view_functions[rule.endpoint](**req.view_args)
>   File "/Users/meee/.pyenv/versions/3.6.5/lib/python3.6/site-packages/blastradius/server/server.py", line 61, in graph_json
>     tf = Terraform(os.getcwd())
>   File "/Users/meee/.pyenv/versions/3.6.5/lib/python3.6/site-packages/blastradius/handlers/terraform.py", line 26, in __init__
>     self.config = hcl.load(config_io)
>   File "/Users/meee/.pyenv/versions/3.6.5/lib/python3.6/site-packages/hcl/api.py", line 51, in load
>     return loads(fp.read())
>   File "/Users/meee/.pyenv/versions/3.6.5/lib/python3.6/site-packages/hcl/api.py", line 62, in loads
>     return HclParser().parse(s)
>   File "/Users/meee/.pyenv/versions/3.6.5/lib/python3.6/site-packages/hcl/parser.py", line 307, in parse
>     return self.yacc.parse(s, lexer=Lexer())
>   File "/Users/meee/.pyenv/versions/3.6.5/lib/python3.6/site-packages/ply/yacc.py", line 331, in parse
>     return self.parseopt_notrack(input, lexer, debug, tracking, tokenfunc)
>   File "/Users/meee/.pyenv/versions/3.6.5/lib/python3.6/site-packages/ply/yacc.py", line 1199, in parseopt_notrack
>     tok = call_errorfunc(self.errorfunc, errtoken, self)
>   File "/Users/meee/.pyenv/versions/3.6.5/lib/python3.6/site-packages/ply/yacc.py", line 193, in call_errorfunc
>     r = errorfunc(token)
>   File "/Users/meee/.pyenv/versions/3.6.5/lib/python3.6/site-packages/hcl/parser.py", line 300, in p_error
>     raise ValueError(msg)
> ValueError: Line 171, column 6458: unexpected RIGHTBRACE
> 127.0.0.1 - - [21/Jan/2019 09:38:14] "GET /graph.json HTTP/1.1" 500 -
>

**Comment by obourdon** [comment]
@red8888 most probably due to a bug/limit in py-hcl module like for [this other issue](https://github.com/28mm/blast-radius/issues/63)
