### ISSUE TITLE
blast fails to run in MacOS

### ISSUE THREAD

**Issue by karlismelderis** [28mm/blast-radius#61]
Any ideas why I'm getting this error:
```
$ blast-radius 
Traceback (most recent call last):
  File "/Users/xxx/Library/Python/2.7/bin/blast-radius", line 14, in <module>
    from blastradius.handlers.dot import DotGraph, Format, DotNode
  File "/Users/xxx/Library/Python/2.7/lib/python/site-packages/blastradius/handlers/dot.py", line 391
    print('Error processing format param: ' + 'p', file=sys.stderr)
                                                       ^
SyntaxError: invalid syntax
```

**Comment by rorynelsonscott** [comment]
Just a guess, but the examples show pip installing to Python 3, looks like Python 2 is trying to run it. That print statement will not work in 2.7.

**Comment by karlismelderis** [comment]
true.
turned out there are some extra steps I missed to get python 3 in MacOS
