### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'groupdict'

### ISSUE THREAD

**Issue by PePoDev** [28mm/blast-radius#86]
Terraform 0.13.2
OS Ubuntu 20.04
Install via pip

```
[2020-09-14 18:24:52,501] ERROR in app: Exception on /graph.svg [GET]
Traceback (most recent call last):
  File "/home/pepodev/.local/lib/python3.8/site-packages/blastradius/handlers/dot.py", line 455, in _module
    return m.groupdict()['module']
AttributeError: 'NoneType' object has no attribute 'groupdict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pepodev/.local/lib/python3.8/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pepodev/.local/lib/python3.8/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pepodev/.local/lib/python3.8/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pepodev/.local/lib/python3.8/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/pepodev/.local/lib/python3.8/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pepodev/.local/lib/python3.8/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pepodev/.local/lib/python3.8/site-packages/blastradius/server/server.py", line 36, in graph_svg
    dot = DotGraph('', file_contents=run_tf_graph())
  File "/home/pepodev/.local/lib/python3.8/site-packages/blastradius/handlers/dot.py", line 56, in __init__
    self.nodes.append(DotNode(e.target))
  File "/home/pepodev/.local/lib/python3.8/site-packages/blastradius/handlers/dot.py", line 415, in __init__
    self.module         = DotNode._module(self.label) # for module groupings. 'root' or 'module.foo.module.bar'
  File "/home/pepodev/.local/lib/python3.8/site-packages/blastradius/handlers/dot.py", line 457, in _module
    raise Exception("None: ", label)
Exception: ('None: ', '[root] module.allow_nfs (close)')
```

**Comment by pinpox** [comment]
Same issue here, did you get it to work?

**Comment by bonzofenix** [comment]
+1

**Comment by vibhuyadav** [comment]
+1

**Comment by pierreyvesv** [comment]
same with 
Terraform 0.13.4
OS windows WSL ubuntu 18.04
Install via pip3
Python 3.6.9
BlastRadius version (0.1.23)

**Comment by lllama** [comment]
I was able to "fix" this by changing the regex to be `r"(\[root\]\s+)*(?P<module>[^.]+)\.(?P<type>\S+)(\.\S+)?"`. I still haven't got it to generate a graph but I think that's my impatience at the moment.

**Comment by szEvEz** [comment]
Anyone got this one working?

**Comment by erSitzt** [comment]
Same here...
Installed with pip3
Terraform v0.14.5
Python 3.6.7
WSL with Ubuntu 18.04
BlastRadius         0.1.23

**Comment by justinTM** [comment]
@28mm

**Comment by KITSDavidGeorge** [comment]
Same. Can get simple aws terraform to work, but anything with a moddule breaks with ssame error. (WSL and Powershell on two different machines):

Terraform: v0.14.3
Python: 3.9.0
[
![Screenshot 2021-02-06 163911](https://user-images.githubusercontent.com/7115435/107124146-ef5bfc00-6899-11eb-9be7-4e14f0eebe19.png)
](url)

**Comment by edvinas-maciulis** [comment]
+1

**Comment by leriksen** [comment]
I got it to render a graph by changing the regex as well, in `blastradius/handlers/dot.py` to be

`m = re.match(r'(\[root\]\s+)*(?P<module>\S+)\.(?P<type>\S+)[. ]\S+', label)`

Not the `[. ]` after the capture for the `<type>` group. The offending label that was crashing for me was

`[root] module.kv (close)`

This character class handles a `.` or a `\s` after a module type

I'll submit a PR maybe by the weekend

**Comment by edvinas-maciulis** [comment]
Thanks @leriksen, also I ended up finding this one - https://github.com/kmussel/blast-radius/. It has some updates and fixes that made it work. There are more commits that may be beneficial to bring back in.

**Comment by PePoDev** [comment]
Closed.
I found alternative to visual infrastructure from Terraform.

> https://github.com/cycloidio/inframap
> https://github.com/pcasteran/terraform-graph-beautifier
