### ISSUE TITLE
Does not start up

### ISSUE THREAD

**Issue by dogmatic69** [28mm/blast-radius#99]
Running on a fresh python:3-alpine box, installed graphviz, terraform and the pip lib.

```
/ # python --version
Python 3.10.2
/ # terraform --version
Terraform v1.0.11
on linux_amd64


Traceback (most recent call last):
  File "/usr/local/bin/blast-radius", line 14, in <module>
    from blastradius.handlers.dot import DotGraph, Format, DotNode
  File "/usr/local/lib/python3.10/site-packages/blastradius/handlers/dot.py", line 12, in <module>
    from blastradius.graph import Graph, Node, Edge
  File "/usr/local/lib/python3.10/site-packages/blastradius/graph.py", line 11, in <module>
    from blastradius.util import Counter
  File "/usr/local/lib/python3.10/site-packages/blastradius/util.py", line 65, in <module>
    class OrderedSet(collections.MutableSet):
AttributeError: module 'collections' has no attribute 'MutableSet'
```

**Comment by luispabon** [comment]
Same here on Ubuntu 22.04 with Python 3.10.

**Comment by markdjones82** [comment]
Same, I'm trying to find the issue.

**Comment by heechankim** [comment]
Same here on Mac M1 Pro with Python 3.10.6

**Comment by Ianyliu** [comment]
This version of Blast Radius doesn't support Python 3.10. The packages it uses are outdated, and some of the code also has to be changed accordingly. 

Since the creator hasn't been active on this repo, I created[ my own repo](https://github.com/Ianyliu/blast-radius-fork) and [Docker image](https://hub.docker.com/repository/docker/ianyliu/blast-radius-fork). 

You can try downloading my version: 

`python3 -m pip install git+https://github.com/Ianyliu/blast-radius-fork`

or run it on Docker: 

`docker run --rm -it -p 5000:5000 \
  -v $(pwd):/data:ro \
  --security-opt apparmor:unconfined \
  --cap-add=SYS_ADMIN \
  ianyliu/blast-radius-fork`

**Comment by chaoscreater** [comment]
Is blast-radius supposed to be a .exe or something? I ran it and it's showing this, because there isn't a file type and therefore no app association...

![image](https://github.com/28mm/blast-radius/assets/18227319/4b5cba50-9856-4d48-bd3a-5f3a423c0b80)

UPDATE:

Got it a bit further by just using Python to run it, but I'm getting this:

![image](https://github.com/28mm/blast-radius/assets/18227319/90e4fbe2-edec-4d44-b382-b940254f2c15)

Tried the above in a brand new installation of Python in a fresh VM and it's the same result.

**Comment by Axel-sys-777** [comment]
In Python 3.10 and above, certain abstract base classes like MutableSet were moved from the collections module to collections.abc. This change was made to better organize the Python standard library.
If you encounter like OP the AttributeError related to MutableSet, MutableMapping, or similar classes, simply update your import statements to use collections.abc instead of collections.
